version: 2

jobs:
  test:
    docker:
      - image: lnhcode/dotnet-cake:2.1-sdk-apline.0.30.0
    steps:
      - checkout
      - run: ./cake.sh -target=test
      
workflows:
  version: 2
  test:
    jobs:
      - test
