version: 2

jobs:
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk-alpine
    steps:
      - checkout
      - run: ./cake.sh -target=test
      
workflows:
  version: 2
  test:
    jobs:
      - test
