version: 2

jobs:
  test:
    docker:
      - image: lnhcode/dotnet2-mono5
    steps:
      - checkout
      - run: ./build.sh -target=test
      
workflows:
  version: 2
  test:
    jobs:
      - test
